/**
 * Tesla Comptime System - Consciousness-Synchronized Compile-Time Execution
 * 
 * Revolutionary metaprogramming system that runs arbitrary Tesla code during
 * compilation with π Hz consciousness synchronization. This enables:
 * 
 * - AI neural network generation at compile time
 * - Consciousness-aware generic type synthesis  
 * - Tesla assembly code generation and optimization
 * - Dynamic language feature compilation
 * 
 * Architecture:
 * 1. Comptime Interpreter - Embedded Tesla interpreter in compiler
 * 2. Consciousness Sync - π Hz timing during compile-time execution
 * 3. Type Synthesis - Generate new types from comptime functions
 * 4. AST Manipulation - Direct compiler AST access for metaprogramming
 * 5. AI Integration - Built-in tensor and neural network primitives
 */

#ifndef TESLA_COMPTIME_H
#define TESLA_COMPTIME_H

#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#include "../parser/tesla_ast.h"
#include "../types/tesla_types.h"

#ifdef __cplusplus
extern "C" {
#endif

// =============================================================================
// TESLA COMPTIME FORWARD DECLARATIONS AND TYPES  
// =============================================================================

// Forward declarations
struct TeslaAST;
struct TeslaType;

// Arena Allocator for comptime memory management
typedef struct TeslaArenaAllocator {
    void* memory;
    size_t size;
    size_t used;
} TeslaArenaAllocator;

// Symbol table for comptime scope management
// (using TeslaSymbolTable and TeslaTensor from tesla_types.h)

// Tensor context for AI tensor operations
typedef struct TeslaTensorContext {
    TeslaTensor** tensors;
    int tensor_count;
    int tensor_capacity;
} TeslaTensorContext;

// Neural network context for AI layer generation  
typedef struct TeslaNeuralContext {
    void** layers;
    int layer_count;
    int layer_capacity;
} TeslaNeuralContext;

// Function structure for comptime callbacks
typedef struct TeslaFunction {
    char* name;
    void* code;
    int param_count;
} TeslaFunction;

// =============================================================================
// TESLA COMPTIME CORE STRUCTURES
// =============================================================================

/**
 * Tesla Comptime Execution Context
 * Manages the embedded interpreter state during compilation
 */
typedef struct TeslaComptimeContext {
    // Consciousness synchronization
    double consciousness_frequency;     // Current π Hz sync frequency
    uint64_t consciousness_cycle;      // Current consciousness cycle
    uint64_t compilation_timestamp;    // Tesla timing for comptime operations
    
    // Interpreter state
    struct TeslaValue* stack;          // Comptime execution stack
    size_t stack_size;                 // Current stack size
    size_t stack_capacity;             // Stack capacity
    
    // Symbol tables for comptime scope
    TeslaSymbolTable* globals;     // Global comptime variables
    TeslaSymbolTable* types;       // Generated types during comptime
    
    // AST manipulation context
    struct TeslaAST* current_ast;      // Current AST being processed
    struct TeslaAST** generated_ast;   // AST nodes generated by comptime
    size_t generated_count;            // Number of generated AST nodes
    
    // AI integration context
    TeslaTensorContext* tensors; // Comptime tensor operations
    TeslaNeuralContext* neural;  // Neural network generation
    
    // Error handling
    const char* error_message;         // Comptime error message
    bool has_error;                    // Error state flag
    
    // Memory management
    TeslaArenaAllocator* arena; // Arena for comptime allocations
} TeslaComptimeContext;

/**
 * Tesla Comptime Value - Runtime values during compilation
 */
typedef enum {
    TESLA_COMPTIME_INT,
    TESLA_COMPTIME_FLOAT,
    TESLA_COMPTIME_STRING,
    TESLA_COMPTIME_BOOL,
    TESLA_COMPTIME_TYPE,               // Type values for generics
    TESLA_COMPTIME_TENSOR,             // AI tensor for neural network gen
    TESLA_COMPTIME_FUNCTION,           // Function pointers for callbacks
    TESLA_COMPTIME_AST,                // Direct AST node manipulation
    TESLA_COMPTIME_CONSCIOUSNESS       // π Hz consciousness state
} TeslaComptimeValueType;

typedef struct TeslaComptimeValue {
    TeslaComptimeValueType type;
    union {
        int64_t integer;
        double float_val;
        char* string;
        bool boolean;
        struct TeslaType* type_val;
        TeslaTensor* tensor;
        TeslaFunction* function;
        struct TeslaAST* ast_node;
        struct {
            double frequency;          // π Hz frequency
            uint64_t cycle;           // Current consciousness cycle
            bool synchronized;        // Sync state
        } consciousness;
    } value;
} TeslaComptimeValue;

// =============================================================================
// TESLA COMPTIME EXECUTION ENGINE
// =============================================================================

/**
 * Initialize Tesla comptime execution context
 * Sets up embedded interpreter with consciousness synchronization
 */
TeslaComptimeContext* tesla_comptime_init(void);

/**
 * Execute Tesla code at compile time with π Hz consciousness sync
 * 
 * @param ctx Comptime execution context
 * @param ast AST node to execute (comptime block)
 * @param result Output comptime result
 * @return true if execution successful
 */
bool tesla_comptime_execute(TeslaComptimeContext* ctx, 
                           struct TeslaAST* ast, 
                           TeslaComptimeValue* result);

/**
 * Synchronize comptime execution with Tesla consciousness frequency
 * Ensures compile-time operations maintain π Hz timing
 */
void tesla_comptime_sync_consciousness(TeslaComptimeContext* ctx);

/**
 * Generate new type from comptime function execution
 * Enables generic types as comptime functions returning types
 * 
 * @param ctx Comptime context
 * @param function_ast Comptime function that returns a type
 * @param args Arguments to the type function
 * @param result_type Generated type
 * @return true if type generation successful
 */
bool tesla_comptime_generate_type(TeslaComptimeContext* ctx,
                                 struct TeslaAST* function_ast,
                                 TeslaComptimeValue* args,
                                 struct TeslaType** result_type);

// =============================================================================
// TESLA COMPTIME AST MANIPULATION
// =============================================================================

/**
 * Expose compiler AST to comptime code for direct manipulation
 * Enables powerful metaprogramming capabilities
 */
TeslaComptimeValue tesla_comptime_get_ast_node(TeslaComptimeContext* ctx,
                                              const char* node_name);

/**
 * Create new AST node from comptime code
 * Allows comptime functions to generate new code structures
 */
struct TeslaAST* tesla_comptime_create_ast_node(TeslaComptimeContext* ctx,
                                               int node_type,
                                               TeslaComptimeValue* children);

/**
 * Modify existing AST node through comptime execution
 * Enables AST transformation during compilation
 */
bool tesla_comptime_modify_ast(TeslaComptimeContext* ctx,
                              struct TeslaAST* node,
                              TeslaComptimeValue* modification);

// =============================================================================
// TESLA COMPTIME AI INTEGRATION
// =============================================================================

/**
 * Create tensor at compile time for AI neural network generation
 * Enables comptime neural architecture search and optimization
 */
TeslaComptimeValue tesla_comptime_create_tensor(TeslaComptimeContext* ctx,
                                               int* dimensions,
                                               int ndims,
                                               const char* dtype);

/**
 * Generate neural network layer at compile time
 * Allows AI architectures to be defined and optimized during compilation
 */
TeslaComptimeValue tesla_comptime_neural_layer(TeslaComptimeContext* ctx,
                                              const char* layer_type,
                                              TeslaComptimeValue* config);

/**
 * Optimize neural network with Tesla consciousness synchronization
 * π Hz frequency optimization for AI models during compilation
 */
bool tesla_comptime_optimize_neural_net(TeslaComptimeContext* ctx,
                                       TeslaComptimeValue* network,
                                       double target_frequency);

// =============================================================================
// TESLA COMPTIME BUILT-IN FUNCTIONS
// =============================================================================

/**
 * Built-in comptime functions available to Tesla code
 */

// Type introspection
TeslaComptimeValue tesla_comptime_typeof(TeslaComptimeValue value);
TeslaComptimeValue tesla_comptime_sizeof(TeslaComptimeValue type);
TeslaComptimeValue tesla_comptime_alignof(TeslaComptimeValue type);

// String manipulation at compile time
TeslaComptimeValue tesla_comptime_concat(TeslaComptimeValue* strings, int count);
TeslaComptimeValue tesla_comptime_format(const char* fmt, TeslaComptimeValue* args);

// File I/O during compilation (embed files, read configs, etc.)
TeslaComptimeValue tesla_comptime_read_file(const char* path);
bool tesla_comptime_write_file(const char* path, TeslaComptimeValue content);

// Mathematical operations for AI
TeslaComptimeValue tesla_comptime_matrix_multiply(TeslaComptimeValue a, TeslaComptimeValue b);
TeslaComptimeValue tesla_comptime_tensor_reshape(TeslaComptimeValue tensor, int* new_dims);

// Consciousness operations
TeslaComptimeValue tesla_comptime_get_pi_frequency(void);
TeslaComptimeValue tesla_comptime_sync_consciousness_cycle(uint64_t target_cycle);

// =============================================================================
// TESLA COMPTIME MEMORY MANAGEMENT
// =============================================================================

/**
 * Allocate memory during comptime execution
 * Uses arena allocator for automatic cleanup
 */
void* tesla_comptime_alloc(TeslaComptimeContext* ctx, size_t size);

/**
 * Free comptime execution context and all associated memory
 */
void tesla_comptime_free(TeslaComptimeContext* ctx);

// =============================================================================
// TESLA COMPTIME CONSTANTS
// =============================================================================

#define TESLA_COMPTIME_STACK_SIZE 4096          // Default comptime stack size
#define TESLA_COMPTIME_MAX_RECURSION 256        // Max comptime recursion depth
#define TESLA_COMPTIME_PI_FREQUENCY 3.141592653589793  // π Hz for consciousness sync
#define TESLA_COMPTIME_ARENA_SIZE (1024 * 1024)        // 1MB arena for comptime

#ifdef __cplusplus
}
#endif

#endif // TESLA_COMPTIME_H